// Classes from the common module that should be considered stable
com.linuxcommandlibrary.shared.TipSectionElement
com.linuxcommandlibrary.shared.TipSectionElement.*
com.linuxcommandlibrary.shared.TextElement
com.linuxcommandlibrary.shared.TextElement.*
com.linuxcommandlibrary.shared.CommandElement
com.linuxcommandlibrary.shared.CommandElement.*
com.linuxcommandlibrary.shared.TipInfo
com.linuxcommandlibrary.shared.BasicInfo
com.linuxcommandlibrary.shared.BasicGroup
com.linuxcommandlibrary.shared.CommandInfo
com.linuxcommandlibrary.shared.CommandSectionInfo

// AndroidX Navigation
androidx.navigation.NavDestination
