import java.io.File

plugins {
    alias(libs.plugins.spotless)
    alias(libs.plugins.kotlin.multiplatform) apply false
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.compose.compiler) apply false
    alias(libs.plugins.compose.multiplatform) apply false
    alias(libs.plugins.paparazzi) apply false
}

group = "com.inspiredandroid"

// Discover swiftformat in the usual Homebrew locations. Skip Swift formatting
// silently on machines that don't have it (e.g. Linux CI doing Android-only builds).
val swiftformatPath: String? =
    listOf(
        "/opt/homebrew/bin/swiftformat",
        "/usr/local/bin/swiftformat",
    ).firstOrNull { File(it).exists() }

configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    kotlin {
        target("**/*.kt")
        // Version.kt is generated by :common:generateVersionFile; formatting it would give
        // spotless an undeclared dependency on that task.
        targetExclude("common/src/commonMain/kotlin/com/linuxcommandlibrary/shared/Version.kt")
        ktlint()
            .editorConfigOverride(
                mapOf(
                    "ktlint_standard_no-wildcard-imports" to "disabled",
                    "ktlint_standard_package-name" to "disabled",
                    "ktlint_standard_function-naming" to "disabled",
                    "ktlint_standard_discouraged-comment-location" to "disabled",
                ),
            )
    }
    kotlinGradle {
        target("**/*.gradle.kts")
        ktlint()
    }

    if (swiftformatPath != null) {
        format("swift") {
            target("iosApp/**/*.swift")
            targetExclude("iosApp/**/.build/**", "iosApp/**/Pods/**", "iosApp/**/build/**")
            nativeCmd(
                "swiftformat",
                swiftformatPath,
                emptyList(),
            )
        }
    } else {
        logger.lifecycle(
            "Spotless: swiftformat not found in /opt/homebrew/bin or /usr/local/bin — Swift formatting skipped. " +
                "Install with: brew install swiftformat",
        )
    }
}
