package com.linuxcommandlibrary.app.ui.composables

/**
 * Category-scoped basics group icon mappings.
 * Keys match category titles (# headers) and group titles (## headers) in basics markdown.
 */
internal val basicGroupIconsByCategory: Map<String, Map<String, AppIcon>> = mapOf(
    "One-liners" to mapOf(
        "Run the previous command with sudo" to AppIcon.MODERATOR,
        "Repeat the last command" to AppIcon.REDO,
        "Fix typo in the previous command" to AppIcon.UNDO,
        "Search command history interactively" to AppIcon.SEARCH_HISTORY,
        "Edit current command line in your editor" to AppIcon.HAND_WITH_PEN,
        "Alias to repeat last command" to AppIcon.CONSOLE,
        "Show most used commands" to AppIcon.TRENDING_UP,
        "Reload shell configuration" to AppIcon.HOME,
        "Check if command exists" to AppIcon.EXE,
        "Change to the previous directory" to AppIcon.HISTORY,
        "Create directory and cd into it" to AppIcon.FOLDER_PATH,
        "Create 100 numbered directories" to AppIcon.CREATE_FOLDER,
        "Quickly backup a file" to AppIcon.FILE_COPY,
        "Empty/truncate a file" to AppIcon.DELETE_FILE,
        "Batch rename files" to AppIcon.FILE_EDIT,
        "Create symlink" to AppIcon.FILE_LINK,
        "Show only directories" to AppIcon.FOLDER_BLACK,
        "List files by modification time" to AppIcon.FOLDER_LIST,
        "Count files in directory" to AppIcon.NUMBERED_LIST,
        "Tree view of directory" to AppIcon.ACCOUNT_TREE,
        "Show file with line numbers" to AppIcon.NUMBERS,
        "Count lines in a file" to AppIcon.CALCULATE,
        "Remove duplicate lines" to AppIcon.DIFFERENCE,
        "Search and replace in files" to AppIcon.SEARCH_IN_FILE,
        "Grep recursively ignoring case" to AppIcon.MANAGE_SEARCH,
        "Find files by name" to AppIcon.SEARCH,
        "Find files larger than 100MB" to AppIcon.FILTER,
        "Delete files older than 30 days" to AppIcon.DELETE,
        "Find and delete empty directories" to AppIcon.DELETE_FOLDER,
        "Find broken symlinks" to AppIcon.LINK_OFF,
        "Find largest files and directories" to AppIcon.STORAGE,
        "Show directory sizes sorted" to AppIcon.SORT,
        "Show disk usage in human-readable format" to AppIcon.HDD,
        "Monitor file changes" to AppIcon.VISIBLE,
        "Watch command output refresh every 2 seconds" to AppIcon.REFRESH,
        "Display clock in terminal" to AppIcon.SCHEDULE,
        "Create a tar.gz backup" to AppIcon.ARCHIVE,
        "Extract a tar.gz archive" to AppIcon.FOLDER_ZIP,
        "Extract any archive format" to AppIcon.REUSE,
        "Split large file" to AppIcon.SPLIT,
        "Reassemble split files" to AppIcon.MERGE,
        "Check file checksum" to AppIcon.CHECK,
        "Encrypt file with gpg" to AppIcon.SECURITY,
        "Generate random password" to AppIcon.USER_PASSWORD,
        "Copy with progress bar" to AppIcon.SYNCHRONIZE,
        "Progress bar for any pipe" to AppIcon.HOURGLASS,
        "Create sparse 10GB file" to AppIcon.CREATE_FILE,
        "Convert DOS to Unix line endings" to AppIcon.SWAP_HORIZ,
        "Pretty-print JSON from stdin" to AppIcon.JSON,
        "Pretty-print XML" to AppIcon.DOCUMENT,
        "Pipe output to clipboard" to AppIcon.CLIPBOARD,
        "Run command in background" to AppIcon.BACKGROUND_TASK,
        "Run detached from terminal" to AppIcon.RESTORE_WINDOW,
        "Kill process by name" to AppIcon.CANCEL,
        "View processes sorted by CPU" to AppIcon.SYSTEM_TASK,
        "Check system uptime" to AppIcon.TIMER,
        "List cron jobs" to AppIcon.CRON,
        "List hardware info" to AppIcon.NETWORK_CARD,
        "Monitor CPU temperature" to AppIcon.THERMOSTAT,
        "Check battery percentage" to AppIcon.BATTERY,
        "Show current timezone" to AppIcon.PUBLIC,
        "Show calendar" to AppIcon.CALENDAR,
        "Show previous, current, and next month" to AppIcon.CALENDAR,
        "Create RAM disk" to AppIcon.MEMORY_SLOT,
        "Disk speed test" to AppIcon.SPEED,
        "Burn ISO to USB" to AppIcon.USB,
        "Securely wipe drive" to AppIcon.DELETE_TRASH,
        "Record terminal session" to AppIcon.RECORD,
        "Replay terminal session" to AppIcon.PLAY,
        "Get your public IP address" to AppIcon.IP_ADDRESS,
        "List open network ports" to AppIcon.LIST_SOCKETS,
        "Download file with resume" to AppIcon.FILE_DOWNLOAD_WHITE,
        "Mount remote directory over SSH" to AppIcon.REMOTE,
        "Spin up a local HTTP server" to AppIcon.HTTP,
        "Quick HTTP server in Ruby" to AppIcon.HTTP,
        "Quick HTTP server in PHP" to AppIcon.HTTP,
        "Quick HTTP server in Node.js" to AppIcon.HTTP,
        "One-liner web server in bash" to AppIcon.CODE,
        "Show weather in terminal" to AppIcon.CLOUD,
        "Get full weather report" to AppIcon.CLOUD,
        "Generate QR code" to AppIcon.QR_CODE,
        "Download YouTube video" to AppIcon.VIDEO,
        "Play YouTube video in terminal" to AppIcon.SMART_DISPLAY,
        "Play a video in terminal as ASCII" to AppIcon.TEXT,
        "Convert image to different format" to AppIcon.IMAGE,
        "Create animated GIF from images" to AppIcon.GIF,
        "Convert video to GIF" to AppIcon.SWITCH_VIDEO,
        "Merge multiple PDFs" to AppIcon.PDF,
        "View PDF in terminal" to AppIcon.FILE_CONTENT,
        "Show current git branch" to AppIcon.GIT,
        "Show git status nicely" to AppIcon.SHOW_PROPERTY,
        "Display system info with ASCII art" to AppIcon.LINUX,
        "Display fortune and cow" to AppIcon.TALK,
        "Rainbow text" to AppIcon.FUN,
        "Simulate slow typing" to AppIcon.KEYBOARD,
        "Matrix digital rain" to AppIcon.FUZZY,
        "Run the train animation" to AppIcon.TRAIN,
        "Play beep" to AppIcon.VOLUME_UP,
    ),
    "AI tools" to mapOf(
        "Coding Agents" to AppIcon.CODE,
        "Agent Tooling" to AppIcon.WORK,
        "AI Assistants" to AppIcon.AGENT,
        "Local LLM Runners" to AppIcon.ELECTRONICS,
        "Image Generation" to AppIcon.IMAGE,
        "Speech & Audio AI" to AppIcon.SOUND_WAVE,
        "AI Terminal Utilities" to AppIcon.CONSOLE,
    ),
    "System information" to mapOf(
        "OS & Kernel" to AppIcon.LINUX,
        "CPU" to AppIcon.ELECTRONICS,
        "Memory" to AppIcon.MEMORY_SLOT,
        "Processes" to AppIcon.SHOW_PROPERTY,
        "Disks & Partitions" to AppIcon.HDD,
        "Hardware" to AppIcon.USB,
        "Battery" to AppIcon.BATTERY,
        "Bluetooth" to AppIcon.BLUETOOTH,
        "Network Interfaces" to AppIcon.LIST_INTERFACES,
        "Kernel & Boot Messages" to AppIcon.RECEIPT_LONG,
    ),
    "System control" to mapOf(
        "Lock screen" to AppIcon.LOCK,
        "Unlock screen" to AppIcon.LOCK_OPEN,
        "Reboot the system" to AppIcon.REFRESH,
        "Shutdown the system" to AppIcon.POWER,
        "Shutdown the system at a specific time" to AppIcon.TIMER,
        "Stop Bluetooth service" to AppIcon.STOP_BLUETOOTH,
        "Start Bluetooth service" to AppIcon.BLUETOOTH_START,
        "Stop wifi service" to AppIcon.STOP_WIFI,
        "Start wifi service" to AppIcon.WIFI_START,
        "Turn off monitor" to AppIcon.TV_OFF,
        "Suspend the system" to AppIcon.PAUSE,
        "Hibernate the system" to AppIcon.HIBERNATE,
        "List running services" to AppIcon.LIST_SOCKETS,
        "Start a service" to AppIcon.PLAY,
        "Stop a service" to AppIcon.CANCEL,
        "Enable service at boot" to AppIcon.TOGGLE_ON,
        "View service logs" to AppIcon.RECEIPT_LONG,
    ),
    "System Recovery" to mapOf(
        "Recovery Strategy" to AppIcon.IDEA,
        "Boot from Rescue Media" to AppIcon.USB,
        "See the Disks" to AppIcon.HDD,
        "Activate LVM & Encrypted Volumes" to AppIcon.SECURITY,
        "Mount the Broken System" to AppIcon.HARD_DRIVE,
        "chroot into the System" to AppIcon.LINUX,
        "Repair the Bootloader" to AppIcon.WORK,
        "Rebuild the initramfs" to AppIcon.SYNCHRONIZE,
        "Rescue & Emergency Mode" to AppIcon.PAUSE,
        "Reset a Forgotten Root Password" to AppIcon.USER_PASSWORD,
        "Filesystem Repair" to AppIcon.HEALING,
        "Fix a Broken /etc/fstab" to AppIcon.DOCUMENT,
        "Repair Broken Package State" to AppIcon.PACKAGE,
        "Diagnose with Logs" to AppIcon.REPORT,
        "Check Disk Health" to AppIcon.STORAGE,
        "Recover Deleted Files & Partitions" to AppIcon.FINGERPRINT,
        "Last Resort: Rescue, then Rebuild" to AppIcon.POWER,
    ),
    "Users & Groups" to mapOf(
        "Creating Users" to AppIcon.ADD_USER,
        "Deleting & Renaming Users" to AppIcon.REMOVE_USER,
        "Modifying Users" to AppIcon.EDIT_USER,
        "Groups" to AppIcon.LIST_GROUPS,
        "Granting sudo" to AppIcon.MODERATOR,
        "Listing Users & Groups" to AppIcon.LIST_USER,
        "Who Am I, Who Is Here" to AppIcon.USER_CIRCLE,
        "Switching Users" to AppIcon.SWITCH_ACCOUNT,
    ),
    "Files & Folders" to mapOf(
        "Navigating" to AppIcon.FOLDER_PATH,
        "Listing Contents" to AppIcon.FOLDER_LIST,
        "Viewing Files" to AppIcon.FILE_CONTENT,
        "Creating" to AppIcon.CREATE_FILE,
        "Copying, Moving, Renaming" to AppIcon.FILE_COPY,
        "Deleting" to AppIcon.DELETE,
        "Links" to AppIcon.FILE_LINK,
        "Permissions & Ownership" to AppIcon.FILE_PERMISSION,
        "Searching File Contents" to AppIcon.SEARCH_IN_FILE,
        "Comparing Files" to AppIcon.DIFFERENCE,
        "Disk Usage" to AppIcon.STORAGE,
        "Mounting Filesystems" to AppIcon.HARD_DRIVE,
        "Editing Text Files" to AppIcon.FILE_EDIT,
    ),
    "Input" to mapOf(
        "Getting Started" to AppIcon.PLAY,
        "Clipboard on X11" to AppIcon.CLIPBOARD,
        "Clipboard on Wayland" to AppIcon.COPY,
        "Moving the Mouse" to AppIcon.MOUSE,
        "Clicking" to AppIcon.CLICK,
        "Typing Text" to AppIcon.KEYBOARD,
        "Pressing Keys" to AppIcon.KEYBOARD_ALT,
    ),
    "Printing" to mapOf(
        "Getting Started" to AppIcon.PLAY,
        "List Printers" to AppIcon.NUMBERED_LIST,
        "Print a file" to AppIcon.PRINT_FILE,
        "Print Options" to AppIcon.SHOW_PROPERTY,
        "View the Print Queue" to AppIcon.VISIBLE,
        "Cancel Print Jobs" to AppIcon.CANCEL,
        "Manage Printers" to AppIcon.SETTINGS,
    ),
    "JSON" to mapOf(
        "Getting Started" to AppIcon.PLAY,
        "Selecting Values" to AppIcon.SHOW_PROPERTY,
        "Filtering & Transforming" to AppIcon.FLOW_CHART,
        "Modifying" to AppIcon.FILE_EDIT,
        "Creating" to AppIcon.NEW,
        "Grepping & Exploring" to AppIcon.SEARCH,
        "Converting" to AppIcon.SYNCHRONIZE,
    ),
    "Network" to mapOf(
        "Interfaces & IP Addresses" to AppIcon.LIST_INTERFACES,
        "Configuring Interfaces" to AppIcon.SETTINGS,
        "Wi-Fi" to AppIcon.WIFI,
        "External IP" to AppIcon.IP_ADDRESS,
        "Testing Connectivity" to AppIcon.PING_PONG,
        "DNS Lookups" to AppIcon.DNS,
        "Downloading Files" to AppIcon.FILE_DOWNLOAD_WHITE,
        "Open Ports & Sockets" to AppIcon.LIST_SOCKETS,
        "Routing" to AppIcon.COMPASS,
        "Bandwidth Usage" to AppIcon.SPEED,
        "Hostname" to AppIcon.TAG,
    ),
    "Search & Find" to mapOf(
        "Getting Started" to AppIcon.PLAY,
        "Find Files by Name" to AppIcon.SEARCH,
        "Find by Type, Size, and Age" to AppIcon.FILTER,
        "Act on What You Find" to AppIcon.WORK,
        "Indexed Search" to AppIcon.SEARCH_SOURCE,
        "Search File Contents" to AppIcon.SEARCH_IN_FILE,
        "Fuzzy Finding" to AppIcon.FUZZY,
        "Find Commands" to AppIcon.MANAGE_SEARCH,
    ),
    "Git" to mapOf(
        "Getting Started" to AppIcon.PLAY,
        "Everyday Workflow" to AppIcon.SAVE,
        "Branches" to AppIcon.ACCOUNT_TREE,
        "Inspecting History" to AppIcon.RECEIPT_LONG,
        "Undoing Things" to AppIcon.UNDO,
        "Stashing" to AppIcon.INVENTORY,
        "Tags" to AppIcon.TAG,
        "Remotes" to AppIcon.CONNECTED,
        "Rewriting History" to AppIcon.HISTORY,
        "Getting Help" to AppIcon.INFO_SMALL,
    ),
    "SSH" to mapOf(
        "Connecting" to AppIcon.CONNECTED,
        "Keys & Passwordless Login" to AppIcon.VPN_KEY,
        "Client Config" to AppIcon.SETTINGS,
        "Transferring Files" to AppIcon.FILE_COPY,
        "Port Forwarding" to AppIcon.SWAP_HORIZ,
        "Jump Hosts & X11" to AppIcon.REMOTE,
        "Keeping Sessions Alive" to AppIcon.REFRESH,
    ),
    "Video & Audio" to mapOf(
        "Screenshots" to AppIcon.SCREENSHOT,
        "Screen Recording" to AppIcon.RECORD,
        "Webcam" to AppIcon.WEBCAM,
        "Playing Audio & Video" to AppIcon.PLAY,
        "Volume" to AppIcon.VOLUME_UP,
        "Recording Audio" to AppIcon.MIC,
        "Speech & Beep" to AppIcon.SOUND_WAVE,
        "Inspect Media Files" to AppIcon.FILE_PREVIEW,
        "Converting with ffmpeg" to AppIcon.SWITCH_VIDEO,
        "Cutting Video" to AppIcon.CONTENT_CUT,
        "Images & Video" to AppIcon.IMAGE,
    ),
    "Package manager" to mapOf(
        "Which Package Manager?" to AppIcon.PUZZLE,
        "Install from repository" to AppIcon.FILE_DOWNLOAD,
        "Install from file" to AppIcon.FILE,
        "Remove/Uninstall" to AppIcon.DELETE,
        "Find a package" to AppIcon.SEARCH,
        "View package info" to AppIcon.INFO_SMALL,
        "Update package lists" to AppIcon.SYNCHRONIZE,
        "Upgrade installed packages" to AppIcon.ARROW_UPWARD,
        "Which package owns a file?" to AppIcon.SEARCH_SOURCE,
        "Add repository source" to AppIcon.ADD_RULE,
        "List installed packages" to AppIcon.NUMBERED_LIST,
        "AUR Helpers" to AppIcon.PACKAGE,
    ),
    "Text Processing" to mapOf(
        "Substitute Text" to AppIcon.FIND_REPLACE,
        "Delete or Print Specific Lines" to AppIcon.DELETE,
        "Extract Fields" to AppIcon.COLUMNS,
        "Filter with Conditions" to AppIcon.FILTER,
        "Sort Lines" to AppIcon.SORT,
        "Find Duplicate Lines" to AppIcon.COPY,
        "Translate or Delete Characters" to AppIcon.SWAP_HORIZ,
        "Compare Files" to AppIcon.DIFFERENCE,
        "Combine Files" to AppIcon.MERGE,
        "Format Text" to AppIcon.TEXT,
        "Number Lines" to AppIcon.NUMBERED_LIST,
        "Count" to AppIcon.NUMBERS,
        "Reverse and Shuffle" to AppIcon.SHUFFLE,
    ),
    "Compression & Archiving" to mapOf(
        "Getting Started" to AppIcon.PLAY,
        "Tar Archives" to AppIcon.ARCHIVE,
        "Choosing a Compressor" to AppIcon.KITCHEN_SCALES,
        "Compressing Single Files" to AppIcon.FILE_DOWNLOAD_WHITE,
        "Working with Compressed Files" to AppIcon.FILE_PREVIEW,
        "Zip Archives" to AppIcon.FOLDER_ZIP,
        "7-Zip Archives" to AppIcon.PACKAGE,
        "Rar Archives" to AppIcon.INVENTORY,
        "Universal Extractors" to AppIcon.REUSE,
        "cpio & ar" to AppIcon.FILE,
    ),
    "Backup & Imaging" to mapOf(
        "Backup Strategy" to AppIcon.INFO_SMALL,
        "File Backups with rsync" to AppIcon.SYNCHRONIZE,
        "Backups over SSH" to AppIcon.CONNECTED,
        "Incremental Snapshots" to AppIcon.REUSE,
        "Archiving Backups" to AppIcon.FILE_DOWNLOAD,
        "Snapshot & Dedup Tools" to AppIcon.STORAGE,
        "Databases & Live Data" to AppIcon.DATABASE,
        "Disk & Partition Imaging" to AppIcon.HDD,
        "Writing Images to USB" to AppIcon.USB,
        "Resilient Imaging & Recovery" to AppIcon.HEALING,
        "Filesystem-level Snapshots" to AppIcon.SAVE,
        "Cloud & Remote Sync" to AppIcon.CLOUD,
        "Verify & Automate" to AppIcon.CHECK,
    ),
    "Hacking tools" to mapOf(
        "Information gathering" to AppIcon.INFO_SMALL,
        "Vulnerability analysis" to AppIcon.HEALING,
        "Web application analysis" to AppIcon.PUBLIC,
        "Password attacks" to AppIcon.SECURITY,
        "Wireless attacks" to AppIcon.WIFI,
        "Exploitation tools" to AppIcon.FLASH,
        "Sniffing & Spoofing" to AppIcon.NETWORK,
        "Forensics" to AppIcon.FINGERPRINT,
        "Reporting tools" to AppIcon.REPORT,
    ),
    "Terminal games" to mapOf(
        "2048" to AppIcon.CONTROLLER,
        "adventure" to AppIcon.CONTROLLER,
        "angband" to AppIcon.CONTROLLER,
        "atc" to AppIcon.CONTROLLER,
        "backgammon" to AppIcon.CONTROLLER,
        "battleship" to AppIcon.CONTROLLER,
        "battlestar" to AppIcon.CONTROLLER,
        "boggle" to AppIcon.CONTROLLER,
        "bombardier" to AppIcon.CONTROLLER,
        "boulder dash" to AppIcon.CONTROLLER,
        "checkers" to AppIcon.CONTROLLER,
        "chess" to AppIcon.CONTROLLER,
        "crawl" to AppIcon.CONTROLLER,
        "cribbage" to AppIcon.CONTROLLER,
        "curseofwar" to AppIcon.CONTROLLER,
        "dopewars" to AppIcon.CONTROLLER,
        "empire" to AppIcon.CONTROLLER,
        "fifteen" to AppIcon.CONTROLLER,
        "go" to AppIcon.CONTROLLER,
        "gomoku" to AppIcon.CONTROLLER,
        "greed" to AppIcon.CONTROLLER,
        "hangman" to AppIcon.CONTROLLER,
        "hunt" to AppIcon.CONTROLLER,
        "interactive fiction" to AppIcon.CONTROLLER,
        "memory" to AppIcon.CONTROLLER,
        "mille bornes" to AppIcon.CONTROLLER,
        "mines" to AppIcon.CONTROLLER,
        "moon-buggy" to AppIcon.CONTROLLER,
        "moria" to AppIcon.CONTROLLER,
        "nbsdgames" to AppIcon.CONTROLLER,
        "nethack" to AppIcon.CONTROLLER,
        "ninvaders" to AppIcon.CONTROLLER,
        "omega" to AppIcon.CONTROLLER,
        "pacman" to AppIcon.CONTROLLER,
        "phantasia" to AppIcon.CONTROLLER,
        "pipes" to AppIcon.CONTROLLER,
        "reversi" to AppIcon.CONTROLLER,
        "robotfindskitten" to AppIcon.CONTROLLER,
        "robots" to AppIcon.CONTROLLER,
        "rogue" to AppIcon.CONTROLLER,
        "sail" to AppIcon.CONTROLLER,
        "ski jump" to AppIcon.CONTROLLER,
        "slashem" to AppIcon.CONTROLLER,
        "snake" to AppIcon.CONTROLLER,
        "solitaire" to AppIcon.CONTROLLER,
        "sos" to AppIcon.CONTROLLER,
        "star trek" to AppIcon.CONTROLLER,
        "sudoku" to AppIcon.CONTROLLER,
        "tetris" to AppIcon.CONTROLLER,
        "typespeed" to AppIcon.CONTROLLER,
        "wumpus" to AppIcon.CONTROLLER,
        "zangband" to AppIcon.CONTROLLER,
    ),
    "Cryptocurrencies" to mapOf(
        "Miners" to AppIcon.GOLDEN_FEVER,
        "Node Software" to AppIcon.ROOT_SERVER,
        "Wallets" to AppIcon.WALLET,
        "Trading Bots" to AppIcon.BOT,
        "Price Tracking" to AppIcon.TRENDING_UP,
    ),
    "Shell Scripting" to mapOf(
        "Script Basics" to AppIcon.INFO_SMALL,
        "Variables" to AppIcon.SHOW_PROPERTY,
        "Quoting" to AppIcon.QUOTE,
        "Special Variables" to AppIcon.FLASH,
        "String Operations" to AppIcon.TEXT,
        "Conditionals" to AppIcon.FLOW_CHART,
        "Loops" to AppIcon.REFRESH,
        "Functions" to AppIcon.PUZZLE,
        "Arrays" to AppIcon.NUMBERED_LIST,
        "Arithmetic" to AppIcon.CALCULATE,
        "Input and Output" to AppIcon.KEYBOARD,
        "Exit Codes and Traps" to AppIcon.CANCEL,
        "Debugging" to AppIcon.BUG,
    ),
    "Tmux" to mapOf(
        "Getting Started" to AppIcon.PLAY,
        "Sessions" to AppIcon.DESKTOP,
        "Windows" to AppIcon.RESTORE_WINDOW,
        "Panes" to AppIcon.SPLITSCREEN,
        "Resizing Panes" to AppIcon.RESIZE,
        "Copy Mode" to AppIcon.CLIPBOARD,
        "Command Mode" to AppIcon.KEYBOARD,
        "Configuration" to AppIcon.SETTINGS,
    ),
    "Regular Expressions" to mapOf(
        "Basic Matching" to AppIcon.SEARCH,
        "Regex Flavors" to AppIcon.DOCUMENT,
        "Anchors" to AppIcon.ANCHOR,
        "Character Classes" to AppIcon.LIST_GROUPS,
        "POSIX Classes" to AppIcon.LINUX,
        "Quantifiers" to AppIcon.PLUS,
        "Groups and Alternation" to AppIcon.GROUP_SELECTED,
        "Escaping" to AppIcon.CODE,
        "Lookahead and Lookbehind" to AppIcon.VISIBLE,
        "Common Examples" to AppIcon.IDEA,
    ),
    "VIM Text Editor" to mapOf(
        "Modes" to AppIcon.TEXT,
        "File Management" to AppIcon.FILE,
        "Navigation" to AppIcon.COMPASS,
        "Insertion" to AppIcon.KEYBOARD,
        "Editing" to AppIcon.HAND_WITH_PEN,
        "Counts & Text Objects" to AppIcon.NUMBERED_LIST,
        "Search and Replace" to AppIcon.SEARCH,
        "Multiple Windows" to AppIcon.RESTORE_WINDOW,
    ),
    "Emacs Text Editor" to mapOf(
        "Getting Started" to AppIcon.PLAY,
        "Navigation" to AppIcon.COMPASS,
        "Editing" to AppIcon.HAND_WITH_PEN,
        "Search and Replace" to AppIcon.SEARCH,
        "Buffers and Windows" to AppIcon.RESTORE_WINDOW,
        "Commands" to AppIcon.CONSOLE,
        "Getting Help" to AppIcon.INFO_SMALL,
    ),
    "Nano Text Editor" to mapOf(
        "Getting Started" to AppIcon.PLAY,
        "Navigation" to AppIcon.COMPASS,
        "File Operations" to AppIcon.FILE_EDIT,
        "Search and Replace" to AppIcon.SEARCH,
        "Editing" to AppIcon.HAND_WITH_PEN,
        "Configuration" to AppIcon.SETTINGS,
    ),
    "Pico Text Editor" to mapOf(
        "Getting Started" to AppIcon.PLAY,
        "Navigation" to AppIcon.COMPASS,
        "File Operations" to AppIcon.FILE_EDIT,
        "Editing" to AppIcon.HAND_WITH_PEN,
        "Search" to AppIcon.SEARCH,
    ),
    "Micro Text Editor" to mapOf(
        "Getting Started" to AppIcon.PLAY,
        "Navigation" to AppIcon.COMPASS,
        "Selection" to AppIcon.GROUP_SELECTED,
        "Editing" to AppIcon.HAND_WITH_PEN,
        "Search and Replace" to AppIcon.SEARCH,
        "Multiple Cursors" to AppIcon.CLICK,
        "Tabs and Splits" to AppIcon.RESTORE_WINDOW,
        "Useful Commands & Options" to AppIcon.INFO_SMALL,
        "Mouse" to AppIcon.MOUSE,
    ),
)
