name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - GUI
        - CLI
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Android
        - iOS
        - Desktop
        - Web
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
    validations:
      required: true
